language: node_js

branches:
  only:
    - master
node_js:
  - "0.12"

before_install:
  - npm install -g hexo

install:
  - npm install

before_script:
  - git config --global user.name 'Marcio Nicolau'
  - git config --global user.email 'marcionicolau@me.com'

script:
  - hexo clean
  - hexo generate

after_success:
  - hexo deploy --silent
