language: node_js

branches:
  only:
    - master
node_js:
  - "0.12"

before_install:
  - npm install -g hexo

install:
  - npm install

before_script:
  - git config --global user.name 'Marcio Nicolau'
  - git config --global user.email 'marcionicolau@me.com'

script:
  - git submodule update
  - hexo clean
  - hexo generate

after_success:
  - mkdir .deploy
  - cd .deploy
  - git clone --depth 1 --branch master --single-branch $DEPLOY_REPO . || (git init && git remote add -t master origin $DEPLOY_REPO)
  - rm -rf ./*
  - cp -r ../public/* .
  - git add -A .
  - git commit -m "Site updated: $(date)"
  - git granch -m master
  - git push -q -u origin master
